/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([IDL.Text], [], []),
  'getMessages' : IDL.Func([], [IDL.Vec(IDL.Tuple(IDL.Text, Time))], ['query']),
  'getMessagesByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  
  return IDL.Service({
    'addMessage' : IDL.Func([IDL.Text], [], []),
    'getMessages' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
        ['query'],
      ),
    'getMessagesByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, Time))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };